const mapa = [
    'VVVVVVVMVMVMVMVVVVVAAAAVVVVVVVVMVMMMMMVVVV',
    'MVMMMMVVVVVMVMVMMMMAAAAVVMMMMVVMVVVVVMVMMM',
    'VVVVVVVMMMMMVMVVVVAAAAAAVVVVMVVMVMMMVMVMMM',
    'VMMMMVVMVVVVVVVVAAAAAAAAAAVVMVVMVVVMVVVVVV',
    'VMVVMVVMVMVMMMVAAAAAAAAAAAAVMMVMMMVMMMMVMM',
    'VMVVMVVVVMVVMVVAAAAAAAAAAAAVVVVVVMVVVVMVVV',
    'VMMVMVVMVMVMAAAAAAAAAAAAAAAAAVVMVMMMMVMMMM',
    'VVVVMMMMVMVMAAAAAAAVVVVAAAAAAAVVVVVVVVVVVV',
    'VMVVMVVVVMAAAAAAAAMMMMVVVAAAAAAAVMMMVMMMMM',
    'VMMMMMMVVVAAAAAAVVMVVVVMMVAAAAAAVMVMVMVVVV',
    'VVVMVVVVAAAAAAAAVVMMMMVVVVVVAAAAVMVMVMMVMM',
    'VVMMAAAAAAAAAAAAVVVVVMVMMMVVVAAAVVVVVVVVVV',
    'MMAAAAAAAAAAAAAAAVMMVMVMVVVVVAAAAAVMMMMVMV',
    'AAAAAAVVAAAAAAAAAAVVVMVVVAAAAAAAAAVVVVMVMV',
    'AAAAAAVVAAAAAAAAAAAAVVVVAAAAAAAAAAAAAVMVMV',
    'AAAAAVVMMMVAAAAAAAAAAAAAAAAAAAAVAAAAAVMMMM',
    'AAAMVVVMVMVAAAAAAAAAAAAAAAAAAAMVMAAAAVVVVV',
    'AAVMVMMMVMVAAAAAAAAAVAAAAAAAAAMVMMAAAAVMMV',
    'VVMMVVVMVMMAAAAAAAAVVVAAAAAAAAMVMAAAAAAVMV',
    'MMMVVMMMVVVAAAAAAVVRVVAAAAAAAAAAAAAAAAAVMM',
    'VVVVVMVVAAAAAAAAAAVVVAAAAAAAAVVVVVAAAAAAVV',
    'MMVMMMVAAAAAAAAAAAAVAAAAAAAAAVMMMMAAAAAAAA',
    'VVVVMVVAAAAMMMAAAAAAAAAAAAAMMMMVVMAAAAAAAA',
    'VMMMMVVAAAVVVMAAAAAAAAAAAAAMVVVVVMAAAVVAAA',
    'VMVVVVMAAAAMMMAAAAAAAAAAAAVMVMMMVMMMVVVVAA',
    'VMVVMMMMVAAAAAAAAAAAAAAAAAMMVMVMVVMVMMMVAA',
    'VVVVMVVMVAAAAAAAAMMMAAAAAAVVVMVVVMMVMVMVAA',
    'AVMVMVVVVVVVVAAAVVVVVVAAAAMMVMMMVMVVVVMVAA',
    'AVMVMMMMVVMMVAAAVVMMVVAAAAVMVVVVVVVMMMMVAA',
    'AAAVVVVMVVMVVAAAMVVMMVAAAAVMMMMMVMMVVVAAAA',
    'AAAVMMVVVVVVVAAAAMVVMVAAAAAAMVVVVMVAAAAAAA',
    'AAAAAAMVAAAAAAAAAAAVVVAAAAAAMMMMMMAAAAMMMM',
    'VAAAAMVAAAAAAAAAAAAAVVAAAAAAVVVVVVAAAMMVVV',
    'VVMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMVVMV',
    'VVMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVMV',
    'VAAAAVVAAAAAAAAAVVVVVVVVVAAAAAAAAAAAAMMVVV',
    'AAAAAVMAAAAAAAAVVMMMVMMMVVVAAAAAMMMAAAMMMM',
    'AAAAAVVVAAAAAAMVVVVVVMVMVMMAAAAVMVMVAAAAAA',
    'AAAVVVVVAAAAAMMVMVVVVMVMVVVMVAAVMVMVAAAAAA',
    'AAAVMMVMMMVAVMVVMVMMMMVMMMVMVAAVMVMVVVVAAA',
    'AVVVVVVVVMVVVVVVVVMVVVVVVMVMVVVMMVMMVVMVAA',
    'AVMMVVMMVVVVVMVMMVVVMMVMVVVVVMVVVVVVMVVVAA'
]

function geraMapa() {
    const table = document.getElementById('mapa')
    const mapaSetado = []
    
    for(let i = 0; i < mapa.length; i++) {
        const row = document.createElement('tr')
        table?.appendChild(row)
        mapaSetado.push([])
        
        for (let j = 0; j < mapa[i].length; j++) {
            const quadro = document.createElement('td')
            const objeto = criaObjetoMapa(mapa[i][j])
            quadro.id = `${i}${j}`
            quadro.style.backgroundColor = objeto.cor
            
            row.appendChild(quadro)
            mapaSetado[i].push(objeto)
        }
    }

    console.log(mapaSetado)
}

function criaObjetoMapa(quadro) {
    switch(quadro) {
        case 'V':
            return {
                peso: 1,
                cor: '#92d050',
                visitado: false,
            }
        case 'M':
            return {
                peso: 60,
                cor: '#948a54',
                visitado: false,
            }
        case 'A': {
            return {
                peso: 10,
                cor: '#548dd4',
                visitado: false,
            }
        }
        default:
            return {
                peso: 0,
                cor: '#c0504d',
                visitado: false,
            }
    }
}

geraMapa()